name: claude-on-at-cove

secrets:
  GITHUB_TOKEN: {}

image:
  setup-scripts:
    - .install-files/install.sh
    # TODO - rm -rf /.install-files
  paths:
    - /usr/local/go/bin
    - /home/agent/go/bin
  env:
    GOROOT: /usr/local/go
    GOPATH: /home/agent/go
    GOPROXY: direct,
    GOSUMDB: off,
    GOFLAGS: -mod=mod
  allowed-domains:
    # Go dependencies
    - gopkg.in