name: claude-on-at-cove
backend: colima

secrets:
  - name: GITHUB_TOKEN

image:
  setup-script:
    - .install-files/install.sh
    # TODO - rm -rf /.install-files
  paths:
    - /usr/local/go/bin
    - /home/agent/go/bin
  env:
    GOROOT: /usr/local/go
    GOPATH: /home/agent/go
  allowed-domains:
    # Go dependencies
    - gopkg.in