// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: attach.proto

package attachpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Activity int32

const (
	Activity_ACTIVITY_UNSPECIFIED Activity = 0
	Activity_RUNNING              Activity = 1
	Activity_WAITING              Activity = 2
	Activity_BLOCKED              Activity = 3
	Activity_DONE                 Activity = 4
)

// Enum value maps for Activity.
var (
	Activity_name = map[int32]string{
		0: "ACTIVITY_UNSPECIFIED",
		1: "RUNNING",
		2: "WAITING",
		3: "BLOCKED",
		4: "DONE",
	}
	Activity_value = map[string]int32{
		"ACTIVITY_UNSPECIFIED": 0,
		"RUNNING":              1,
		"WAITING":              2,
		"BLOCKED":              3,
		"DONE":                 4,
	}
)

func (x Activity) Enum() *Activity {
	p := new(Activity)
	*p = x
	return p
}

func (x Activity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Activity) Descriptor() protoreflect.EnumDescriptor {
	return file_attach_proto_enumTypes[0].Descriptor()
}

func (Activity) Type() protoreflect.EnumType {
	return &file_attach_proto_enumTypes[0]
}

func (x Activity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Activity.Descriptor instead.
func (Activity) EnumDescriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{0}
}

type StatusUp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*StatusUp_Status
	//	*StatusUp_Heartbeat
	Msg           isStatusUp_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUp) Reset() {
	*x = StatusUp{}
	mi := &file_attach_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUp) ProtoMessage() {}

func (x *StatusUp) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUp.ProtoReflect.Descriptor instead.
func (*StatusUp) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{0}
}

func (x *StatusUp) GetMsg() isStatusUp_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *StatusUp) GetStatus() Activity {
	if x != nil {
		if x, ok := x.Msg.(*StatusUp_Status); ok {
			return x.Status
		}
	}
	return Activity_ACTIVITY_UNSPECIFIED
}

func (x *StatusUp) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*StatusUp_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isStatusUp_Msg interface {
	isStatusUp_Msg()
}

type StatusUp_Status struct {
	Status Activity `protobuf:"varint,1,opt,name=status,proto3,enum=harbor.attach.v1.Activity,oneof"`
}

type StatusUp_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*StatusUp_Status) isStatusUp_Msg() {}

func (*StatusUp_Heartbeat) isStatusUp_Msg() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_attach_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{1}
}

type ControlDown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControlDown_Wake
	//	*ControlDown_Teardown
	//	*ControlDown_Tier
	//	*ControlDown_Rotate
	Msg           isControlDown_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlDown) Reset() {
	*x = ControlDown{}
	mi := &file_attach_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlDown) ProtoMessage() {}

func (x *ControlDown) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlDown.ProtoReflect.Descriptor instead.
func (*ControlDown) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{2}
}

func (x *ControlDown) GetMsg() isControlDown_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControlDown) GetWake() *Wake {
	if x != nil {
		if x, ok := x.Msg.(*ControlDown_Wake); ok {
			return x.Wake
		}
	}
	return nil
}

func (x *ControlDown) GetTeardown() *Teardown {
	if x != nil {
		if x, ok := x.Msg.(*ControlDown_Teardown); ok {
			return x.Teardown
		}
	}
	return nil
}

func (x *ControlDown) GetTier() *TierChanged {
	if x != nil {
		if x, ok := x.Msg.(*ControlDown_Tier); ok {
			return x.Tier
		}
	}
	return nil
}

func (x *ControlDown) GetRotate() *RotateToken {
	if x != nil {
		if x, ok := x.Msg.(*ControlDown_Rotate); ok {
			return x.Rotate
		}
	}
	return nil
}

type isControlDown_Msg interface {
	isControlDown_Msg()
}

type ControlDown_Wake struct {
	Wake *Wake `protobuf:"bytes,1,opt,name=wake,proto3,oneof"`
}

type ControlDown_Teardown struct {
	Teardown *Teardown `protobuf:"bytes,2,opt,name=teardown,proto3,oneof"`
}

type ControlDown_Tier struct {
	Tier *TierChanged `protobuf:"bytes,3,opt,name=tier,proto3,oneof"`
}

type ControlDown_Rotate struct {
	Rotate *RotateToken `protobuf:"bytes,4,opt,name=rotate,proto3,oneof"` // reserved
}

func (*ControlDown_Wake) isControlDown_Msg() {}

func (*ControlDown_Teardown) isControlDown_Msg() {}

func (*ControlDown_Tier) isControlDown_Msg() {}

func (*ControlDown_Rotate) isControlDown_Msg() {}

type Wake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wake) Reset() {
	*x = Wake{}
	mi := &file_attach_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wake) ProtoMessage() {}

func (x *Wake) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wake.ProtoReflect.Descriptor instead.
func (*Wake) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{3}
}

type Teardown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Teardown) Reset() {
	*x = Teardown{}
	mi := &file_attach_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Teardown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teardown) ProtoMessage() {}

func (x *Teardown) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teardown.ProtoReflect.Descriptor instead.
func (*Teardown) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{4}
}

func (x *Teardown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TierChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          int32                  `protobuf:"varint,1,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TierChanged) Reset() {
	*x = TierChanged{}
	mi := &file_attach_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierChanged) ProtoMessage() {}

func (x *TierChanged) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierChanged.ProtoReflect.Descriptor instead.
func (*TierChanged) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{5}
}

func (x *TierChanged) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

type RotateToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateToken) Reset() {
	*x = RotateToken{}
	mi := &file_attach_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateToken) ProtoMessage() {}

func (x *RotateToken) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateToken.ProtoReflect.Descriptor instead.
func (*RotateToken) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{6}
}

func (x *RotateToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_attach_proto protoreflect.FileDescriptor

const file_attach_proto_rawDesc = "" +
	"\n" +
	"\fattach.proto\x12\x10harbor.attach.v1\"\x84\x01\n" +
	"\bStatusUp\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.harbor.attach.v1.ActivityH\x00R\x06status\x12;\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1b.harbor.attach.v1.HeartbeatH\x00R\theartbeatB\x05\n" +
	"\x03msg\"\v\n" +
	"\tHeartbeat\"\xea\x01\n" +
	"\vControlDown\x12,\n" +
	"\x04wake\x18\x01 \x01(\v2\x16.harbor.attach.v1.WakeH\x00R\x04wake\x128\n" +
	"\bteardown\x18\x02 \x01(\v2\x1a.harbor.attach.v1.TeardownH\x00R\bteardown\x123\n" +
	"\x04tier\x18\x03 \x01(\v2\x1d.harbor.attach.v1.TierChangedH\x00R\x04tier\x127\n" +
	"\x06rotate\x18\x04 \x01(\v2\x1d.harbor.attach.v1.RotateTokenH\x00R\x06rotateB\x05\n" +
	"\x03msg\"\x06\n" +
	"\x04Wake\"\"\n" +
	"\bTeardown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"!\n" +
	"\vTierChanged\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\x05R\x04tier\"#\n" +
	"\vRotateToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token*U\n" +
	"\bActivity\x12\x18\n" +
	"\x14ACTIVITY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\v\n" +
	"\aWAITING\x10\x02\x12\v\n" +
	"\aBLOCKED\x10\x03\x12\b\n" +
	"\x04DONE\x10\x042R\n" +
	"\aRuntime\x12G\n" +
	"\x06Attach\x12\x1a.harbor.attach.v1.StatusUp\x1a\x1d.harbor.attach.v1.ControlDown(\x010\x01B?Z=github.com/aethons-tools/cove/internal/harbor/attach/attachpbb\x06proto3"

var (
	file_attach_proto_rawDescOnce sync.Once
	file_attach_proto_rawDescData []byte
)

func file_attach_proto_rawDescGZIP() []byte {
	file_attach_proto_rawDescOnce.Do(func() {
		file_attach_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attach_proto_rawDesc), len(file_attach_proto_rawDesc)))
	})
	return file_attach_proto_rawDescData
}

var file_attach_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_attach_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_attach_proto_goTypes = []any{
	(Activity)(0),       // 0: harbor.attach.v1.Activity
	(*StatusUp)(nil),    // 1: harbor.attach.v1.StatusUp
	(*Heartbeat)(nil),   // 2: harbor.attach.v1.Heartbeat
	(*ControlDown)(nil), // 3: harbor.attach.v1.ControlDown
	(*Wake)(nil),        // 4: harbor.attach.v1.Wake
	(*Teardown)(nil),    // 5: harbor.attach.v1.Teardown
	(*TierChanged)(nil), // 6: harbor.attach.v1.TierChanged
	(*RotateToken)(nil), // 7: harbor.attach.v1.RotateToken
}
var file_attach_proto_depIdxs = []int32{
	0, // 0: harbor.attach.v1.StatusUp.status:type_name -> harbor.attach.v1.Activity
	2, // 1: harbor.attach.v1.StatusUp.heartbeat:type_name -> harbor.attach.v1.Heartbeat
	4, // 2: harbor.attach.v1.ControlDown.wake:type_name -> harbor.attach.v1.Wake
	5, // 3: harbor.attach.v1.ControlDown.teardown:type_name -> harbor.attach.v1.Teardown
	6, // 4: harbor.attach.v1.ControlDown.tier:type_name -> harbor.attach.v1.TierChanged
	7, // 5: harbor.attach.v1.ControlDown.rotate:type_name -> harbor.attach.v1.RotateToken
	1, // 6: harbor.attach.v1.Runtime.Attach:input_type -> harbor.attach.v1.StatusUp
	3, // 7: harbor.attach.v1.Runtime.Attach:output_type -> harbor.attach.v1.ControlDown
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_attach_proto_init() }
func file_attach_proto_init() {
	if File_attach_proto != nil {
		return
	}
	file_attach_proto_msgTypes[0].OneofWrappers = []any{
		(*StatusUp_Status)(nil),
		(*StatusUp_Heartbeat)(nil),
	}
	file_attach_proto_msgTypes[2].OneofWrappers = []any{
		(*ControlDown_Wake)(nil),
		(*ControlDown_Teardown)(nil),
		(*ControlDown_Tier)(nil),
		(*ControlDown_Rotate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attach_proto_rawDesc), len(file_attach_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attach_proto_goTypes,
		DependencyIndexes: file_attach_proto_depIdxs,
		EnumInfos:         file_attach_proto_enumTypes,
		MessageInfos:      file_attach_proto_msgTypes,
	}.Build()
	File_attach_proto = out.File
	file_attach_proto_goTypes = nil
	file_attach_proto_depIdxs = nil
}
