// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: attach.proto

// The proto package stays harbor.attach.v1 through the Harbor → Jam rename: it
// is the gRPC wire name (/harbor.attach.v1.Runtime/Attach) that cove-master in
// already-built cove images dials, so renaming it would break running coves.
// See docs/usage/jam/renamed-from-harbor.md.

package attachpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Activity int32

const (
	Activity_ACTIVITY_UNSPECIFIED Activity = 0
	Activity_RUNNING              Activity = 1
	Activity_WAITING              Activity = 2
	Activity_BLOCKED              Activity = 3
	Activity_DONE                 Activity = 4
)

// Enum value maps for Activity.
var (
	Activity_name = map[int32]string{
		0: "ACTIVITY_UNSPECIFIED",
		1: "RUNNING",
		2: "WAITING",
		3: "BLOCKED",
		4: "DONE",
	}
	Activity_value = map[string]int32{
		"ACTIVITY_UNSPECIFIED": 0,
		"RUNNING":              1,
		"WAITING":              2,
		"BLOCKED":              3,
		"DONE":                 4,
	}
)

func (x Activity) Enum() *Activity {
	p := new(Activity)
	*p = x
	return p
}

func (x Activity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Activity) Descriptor() protoreflect.EnumDescriptor {
	return file_attach_proto_enumTypes[0].Descriptor()
}

func (Activity) Type() protoreflect.EnumType {
	return &file_attach_proto_enumTypes[0]
}

func (x Activity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Activity.Descriptor instead.
func (Activity) EnumDescriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{0}
}

type StatusUp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*StatusUp_Status
	//	*StatusUp_Heartbeat
	//	*StatusUp_Event
	//	*StatusUp_Connector
	Msg           isStatusUp_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUp) Reset() {
	*x = StatusUp{}
	mi := &file_attach_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUp) ProtoMessage() {}

func (x *StatusUp) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUp.ProtoReflect.Descriptor instead.
func (*StatusUp) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{0}
}

func (x *StatusUp) GetMsg() isStatusUp_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *StatusUp) GetStatus() Activity {
	if x != nil {
		if x, ok := x.Msg.(*StatusUp_Status); ok {
			return x.Status
		}
	}
	return Activity_ACTIVITY_UNSPECIFIED
}

func (x *StatusUp) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*StatusUp_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *StatusUp) GetEvent() *SessionEvent {
	if x != nil {
		if x, ok := x.Msg.(*StatusUp_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *StatusUp) GetConnector() *ConnectorApplied {
	if x != nil {
		if x, ok := x.Msg.(*StatusUp_Connector); ok {
			return x.Connector
		}
	}
	return nil
}

type isStatusUp_Msg interface {
	isStatusUp_Msg()
}

type StatusUp_Status struct {
	Status Activity `protobuf:"varint,1,opt,name=status,proto3,enum=harbor.attach.v1.Activity,oneof"`
}

type StatusUp_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type StatusUp_Event struct {
	Event *SessionEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type StatusUp_Connector struct {
	Connector *ConnectorApplied `protobuf:"bytes,4,opt,name=connector,proto3,oneof"`
}

func (*StatusUp_Status) isStatusUp_Msg() {}

func (*StatusUp_Heartbeat) isStatusUp_Msg() {}

func (*StatusUp_Event) isStatusUp_Msg() {}

func (*StatusUp_Connector) isStatusUp_Msg() {}

// ConnectorApplied reports the fingerprint (snippet.Fingerprint) of the
// connector cove-master applied to the agent's most recent spawn. Jam compares it
// with the role's current connector to flag a stale studio.
type ConnectorApplied struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorApplied) Reset() {
	*x = ConnectorApplied{}
	mi := &file_attach_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorApplied) ProtoMessage() {}

func (x *ConnectorApplied) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorApplied.ProtoReflect.Descriptor instead.
func (*ConnectorApplied) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectorApplied) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

// SessionEvent is one line of the agent's claude stream-json stdout.
type SessionEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`                      // random per cove-master process: 32 lowercase hex chars
	Seq            uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                               // monotonic per stream_id, from 1
	Turn           uint32                 `protobuf:"varint,3,opt,name=turn,proto3" json:"turn,omitempty"`                                             // claude invocation number, from 1
	ObservedUnixMs int64                  `protobuf:"varint,4,opt,name=observed_unix_ms,json=observedUnixMs,proto3" json:"observed_unix_ms,omitempty"` // when cove-master read the line
	Raw            []byte                 `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`                                                // the line, no trailing newline, secrets redacted
	TruncatedBytes uint64                 `protobuf:"varint,6,opt,name=truncated_bytes,json=truncatedBytes,proto3" json:"truncated_bytes,omitempty"`   // bytes dropped from raw; 0 = intact
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_attach_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{2}
}

func (x *SessionEvent) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *SessionEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SessionEvent) GetTurn() uint32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *SessionEvent) GetObservedUnixMs() int64 {
	if x != nil {
		return x.ObservedUnixMs
	}
	return 0
}

func (x *SessionEvent) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *SessionEvent) GetTruncatedBytes() uint64 {
	if x != nil {
		return x.TruncatedBytes
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_attach_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{3}
}

type ControlDown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControlDown_Wake
	//	*ControlDown_Teardown
	//	*ControlDown_Tier
	//	*ControlDown_Rotate
	//	*ControlDown_Ack
	Msg           isControlDown_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlDown) Reset() {
	*x = ControlDown{}
	mi := &file_attach_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlDown) ProtoMessage() {}

func (x *ControlDown) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlDown.ProtoReflect.Descriptor instead.
func (*ControlDown) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{4}
}

func (x *ControlDown) GetMsg() isControlDown_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControlDown) GetWake() *Wake {
	if x != nil {
		if x, ok := x.Msg.(*ControlDown_Wake); ok {
			return x.Wake
		}
	}
	return nil
}

func (x *ControlDown) GetTeardown() *Teardown {
	if x != nil {
		if x, ok := x.Msg.(*ControlDown_Teardown); ok {
			return x.Teardown
		}
	}
	return nil
}

func (x *ControlDown) GetTier() *TierChanged {
	if x != nil {
		if x, ok := x.Msg.(*ControlDown_Tier); ok {
			return x.Tier
		}
	}
	return nil
}

func (x *ControlDown) GetRotate() *RotateToken {
	if x != nil {
		if x, ok := x.Msg.(*ControlDown_Rotate); ok {
			return x.Rotate
		}
	}
	return nil
}

func (x *ControlDown) GetAck() *EventAck {
	if x != nil {
		if x, ok := x.Msg.(*ControlDown_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isControlDown_Msg interface {
	isControlDown_Msg()
}

type ControlDown_Wake struct {
	Wake *Wake `protobuf:"bytes,1,opt,name=wake,proto3,oneof"`
}

type ControlDown_Teardown struct {
	Teardown *Teardown `protobuf:"bytes,2,opt,name=teardown,proto3,oneof"`
}

type ControlDown_Tier struct {
	Tier *TierChanged `protobuf:"bytes,3,opt,name=tier,proto3,oneof"`
}

type ControlDown_Rotate struct {
	Rotate *RotateToken `protobuf:"bytes,4,opt,name=rotate,proto3,oneof"` // reserved
}

type ControlDown_Ack struct {
	Ack *EventAck `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

func (*ControlDown_Wake) isControlDown_Msg() {}

func (*ControlDown_Teardown) isControlDown_Msg() {}

func (*ControlDown_Tier) isControlDown_Msg() {}

func (*ControlDown_Rotate) isControlDown_Msg() {}

func (*ControlDown_Ack) isControlDown_Msg() {}

// EventAck is cumulative: every event of stream_id with seq <= this is durable.
type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_attach_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{5}
}

func (x *EventAck) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *EventAck) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Wake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wake) Reset() {
	*x = Wake{}
	mi := &file_attach_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wake) ProtoMessage() {}

func (x *Wake) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wake.ProtoReflect.Descriptor instead.
func (*Wake) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{6}
}

type Teardown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Teardown) Reset() {
	*x = Teardown{}
	mi := &file_attach_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Teardown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teardown) ProtoMessage() {}

func (x *Teardown) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teardown.ProtoReflect.Descriptor instead.
func (*Teardown) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{7}
}

func (x *Teardown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TierChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          int32                  `protobuf:"varint,1,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TierChanged) Reset() {
	*x = TierChanged{}
	mi := &file_attach_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierChanged) ProtoMessage() {}

func (x *TierChanged) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierChanged.ProtoReflect.Descriptor instead.
func (*TierChanged) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{8}
}

func (x *TierChanged) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

type RotateToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateToken) Reset() {
	*x = RotateToken{}
	mi := &file_attach_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateToken) ProtoMessage() {}

func (x *RotateToken) ProtoReflect() protoreflect.Message {
	mi := &file_attach_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateToken.ProtoReflect.Descriptor instead.
func (*RotateToken) Descriptor() ([]byte, []int) {
	return file_attach_proto_rawDescGZIP(), []int{9}
}

func (x *RotateToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_attach_proto protoreflect.FileDescriptor

const file_attach_proto_rawDesc = "" +
	"\n" +
	"\fattach.proto\x12\x10harbor.attach.v1\"\x80\x02\n" +
	"\bStatusUp\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.harbor.attach.v1.ActivityH\x00R\x06status\x12;\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1b.harbor.attach.v1.HeartbeatH\x00R\theartbeat\x126\n" +
	"\x05event\x18\x03 \x01(\v2\x1e.harbor.attach.v1.SessionEventH\x00R\x05event\x12B\n" +
	"\tconnector\x18\x04 \x01(\v2\".harbor.attach.v1.ConnectorAppliedH\x00R\tconnectorB\x05\n" +
	"\x03msg\"4\n" +
	"\x10ConnectorApplied\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\"\xb6\x01\n" +
	"\fSessionEvent\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04turn\x18\x03 \x01(\rR\x04turn\x12(\n" +
	"\x10observed_unix_ms\x18\x04 \x01(\x03R\x0eobservedUnixMs\x12\x10\n" +
	"\x03raw\x18\x05 \x01(\fR\x03raw\x12'\n" +
	"\x0ftruncated_bytes\x18\x06 \x01(\x04R\x0etruncatedBytes\"\v\n" +
	"\tHeartbeat\"\x9a\x02\n" +
	"\vControlDown\x12,\n" +
	"\x04wake\x18\x01 \x01(\v2\x16.harbor.attach.v1.WakeH\x00R\x04wake\x128\n" +
	"\bteardown\x18\x02 \x01(\v2\x1a.harbor.attach.v1.TeardownH\x00R\bteardown\x123\n" +
	"\x04tier\x18\x03 \x01(\v2\x1d.harbor.attach.v1.TierChangedH\x00R\x04tier\x127\n" +
	"\x06rotate\x18\x04 \x01(\v2\x1d.harbor.attach.v1.RotateTokenH\x00R\x06rotate\x12.\n" +
	"\x03ack\x18\x05 \x01(\v2\x1a.harbor.attach.v1.EventAckH\x00R\x03ackB\x05\n" +
	"\x03msg\"9\n" +
	"\bEventAck\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"\x06\n" +
	"\x04Wake\"\"\n" +
	"\bTeardown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"!\n" +
	"\vTierChanged\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\x05R\x04tier\"#\n" +
	"\vRotateToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token*U\n" +
	"\bActivity\x12\x18\n" +
	"\x14ACTIVITY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\v\n" +
	"\aWAITING\x10\x02\x12\v\n" +
	"\aBLOCKED\x10\x03\x12\b\n" +
	"\x04DONE\x10\x042R\n" +
	"\aRuntime\x12G\n" +
	"\x06Attach\x12\x1a.harbor.attach.v1.StatusUp\x1a\x1d.harbor.attach.v1.ControlDown(\x010\x01B<Z:github.com/aethons-tools/cove/internal/jam/attach/attachpbb\x06proto3"

var (
	file_attach_proto_rawDescOnce sync.Once
	file_attach_proto_rawDescData []byte
)

func file_attach_proto_rawDescGZIP() []byte {
	file_attach_proto_rawDescOnce.Do(func() {
		file_attach_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attach_proto_rawDesc), len(file_attach_proto_rawDesc)))
	})
	return file_attach_proto_rawDescData
}

var file_attach_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_attach_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_attach_proto_goTypes = []any{
	(Activity)(0),            // 0: harbor.attach.v1.Activity
	(*StatusUp)(nil),         // 1: harbor.attach.v1.StatusUp
	(*ConnectorApplied)(nil), // 2: harbor.attach.v1.ConnectorApplied
	(*SessionEvent)(nil),     // 3: harbor.attach.v1.SessionEvent
	(*Heartbeat)(nil),        // 4: harbor.attach.v1.Heartbeat
	(*ControlDown)(nil),      // 5: harbor.attach.v1.ControlDown
	(*EventAck)(nil),         // 6: harbor.attach.v1.EventAck
	(*Wake)(nil),             // 7: harbor.attach.v1.Wake
	(*Teardown)(nil),         // 8: harbor.attach.v1.Teardown
	(*TierChanged)(nil),      // 9: harbor.attach.v1.TierChanged
	(*RotateToken)(nil),      // 10: harbor.attach.v1.RotateToken
}
var file_attach_proto_depIdxs = []int32{
	0,  // 0: harbor.attach.v1.StatusUp.status:type_name -> harbor.attach.v1.Activity
	4,  // 1: harbor.attach.v1.StatusUp.heartbeat:type_name -> harbor.attach.v1.Heartbeat
	3,  // 2: harbor.attach.v1.StatusUp.event:type_name -> harbor.attach.v1.SessionEvent
	2,  // 3: harbor.attach.v1.StatusUp.connector:type_name -> harbor.attach.v1.ConnectorApplied
	7,  // 4: harbor.attach.v1.ControlDown.wake:type_name -> harbor.attach.v1.Wake
	8,  // 5: harbor.attach.v1.ControlDown.teardown:type_name -> harbor.attach.v1.Teardown
	9,  // 6: harbor.attach.v1.ControlDown.tier:type_name -> harbor.attach.v1.TierChanged
	10, // 7: harbor.attach.v1.ControlDown.rotate:type_name -> harbor.attach.v1.RotateToken
	6,  // 8: harbor.attach.v1.ControlDown.ack:type_name -> harbor.attach.v1.EventAck
	1,  // 9: harbor.attach.v1.Runtime.Attach:input_type -> harbor.attach.v1.StatusUp
	5,  // 10: harbor.attach.v1.Runtime.Attach:output_type -> harbor.attach.v1.ControlDown
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_attach_proto_init() }
func file_attach_proto_init() {
	if File_attach_proto != nil {
		return
	}
	file_attach_proto_msgTypes[0].OneofWrappers = []any{
		(*StatusUp_Status)(nil),
		(*StatusUp_Heartbeat)(nil),
		(*StatusUp_Event)(nil),
		(*StatusUp_Connector)(nil),
	}
	file_attach_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlDown_Wake)(nil),
		(*ControlDown_Teardown)(nil),
		(*ControlDown_Tier)(nil),
		(*ControlDown_Rotate)(nil),
		(*ControlDown_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attach_proto_rawDesc), len(file_attach_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attach_proto_goTypes,
		DependencyIndexes: file_attach_proto_depIdxs,
		EnumInfos:         file_attach_proto_enumTypes,
		MessageInfos:      file_attach_proto_msgTypes,
	}.Build()
	File_attach_proto = out.File
	file_attach_proto_goTypes = nil
	file_attach_proto_depIdxs = nil
}
