// Package attachpb holds the generated gRPC types for the managed-cove Attach
// stream (harbor.attach.v1 — the wire name keeps "harbor"; see ../proto/attach.proto). Generated by `buf generate` from ../proto/attach.proto;
// do not edit by hand. Regenerate per docs/DEVELOPMENT.md.
package attachpb
